 export const catalog_list = [
	{
		id:     1,
		name:   "Твайлайт",
		color:  "Белый",
        kind:   "Земная пони",
		price:  "199.99",
		is_new: true,
    },
	{
		id:     2,
		name:   "Единорожка",
		color:  "Красный",
        kind:   "Единорог",
		price:  "191.00",
		is_new: true,
    },
	{
		id:     3,
		name:   "Летящий конь",
		color:  "Зеленый",
        kind:   "Пегас",
		price:  "180.05",
		is_new: true,
    },
	{
		id:     4,
		name:   "Белый пони",
		color:  "Розовый",
        kind:   "Аликорн",
		price:  "190.12",
		is_new: true,
    },
	{
		id:     5,
		name:   "Пони зеленый",
		color:  "Бежевый",
        kind:   "Кирин",
		price:  "199.18",
		is_new: false,
    },
	{
		id:     6,
		name:   "Пони-принц",
		color:  "Бежевый",
        kind:   "Кирин",
		price:  "250.00",
		is_new: true,
    },
	{
		id:     7,
		name:   "Твайлайт",
		color:  "Белый",
        kind:   "Земная пони",
		price:  "199.99",
		is_new: true,
    },
	{
		id:     8,
		name:   "Единорожка",
		color:  "Зеленый",
        kind:   "Единорог",
		price:  "191.00",
		is_new: true,
    },
	{
		id:     9,
		name:   "Летящий конь",
		color:  "Красный",
        kind:   "Пегас",
		price:  "180.05",
		is_new: true,
    },
	{
		id:     10,
		name:   "Белый пони",
		color:  "Бежевый",
        kind:   "Аликорн",
		price:  "190.12",
		is_new: true,
    },
	{
		id:     11,
		name:   "Пони зеленый",
		color:  "Розовый",
        kind:   "Кирин",
		price:  "199.18",
		is_new: false,
    },
	{
		id:     12,
		name:   "Пони-принц",
		color:  "Бежевый",
        kind:   "Кирин",
		price:  "250.00",
		is_new: true,
    },
	{
		id:     13,
		name:   "Твайлайт",
		color:  "Красный",
        kind:   "Земная пони",
		price:  "199.99",
		is_new: true,
    },
	{
		id:     14,
		name:   "Единорожка",
		color:  "Белый",
        kind:   "Единорог",
		price:  "191.00",
		is_new: true,
    },
	{
		id:     15,
		name:   "Летящий конь",
		color:  "Розовый",
        kind:   "Пегас",
		price:  "180.05",
		is_new: true,
    },
	{
		id:     16,
		name:   "Белый пони",
		color:  "Зеленый",
        kind:   "Аликорн",
		price:  "190.12",
		is_new: true,
    },
	{
		id:     17,
		name:   "Пони зеленый",
		color:  "Лиловый",
        kind:   "Кирин",
		price:  "199.18",
		is_new: false,
    },
	{
		id:     18,
		name:   "Пони-принц",
		color:  "Бирюзовый",
        kind:   "Кирин",
		price:  "250.00",
		is_new: true,
    },
	{
		id:     19,
		name:   "Твайлайт",
		color:  "Красный",
        kind:   "Земная пони",
		price:  "199.99",
		is_new: true,
    },
	{
		id:     20,
		name:   "Единорожка",
		color:  "Белый",
        kind:   "Единорог",
		price:  "191.00",
		is_new: true,
    },
	{
		id:     21,
		name:   "Летящий конь",
		color:  "Розовый",
        kind:   "Пегас",
		price:  "180.05",
		is_new: true,
    },
	{
		id:     22,
		name:   "Белый пони",
		color:  "Зеленый",
        kind:   "Аликорн",
		price:  "190.12",
		is_new: true,
    },
	{
		id:     23,
		name:   "Пони зеленый",
		color:  "Голубой",
        kind:   "Кирин",
		price:  "199.18",
		is_new: false,
    },
	{
		id:     24,
		name:   "Пони-принц",
		color:  "Лиловый",
        kind:   "Кирин",
		price:  "250.00",
		is_new: true,
    },
	{
		id:     25,
		name:   "Твайлайт",
		color:  "Желтый",
        kind:   "Земная пони",
		price:  "199.99",
		is_new: true,
    },
	{
		id:     26,
		name:   "Единорожка",
		color:  "Белый",
        kind:   "Единорог",
		price:  "191.00",
		is_new: true,
    },
	{
		id:     27,
		name:   "Летящий конь",
		color:  "Зеленый",
        kind:   "Пегас",
		price:  "180.05",
		is_new: true,
    },
	{
		id:     28,
		name:   "Белый пони",
		color:  "Белый",
        kind:   "Аликорн",
		price:  "190.12",
		is_new: true,
    },
	{
		id:     29,
		name:   "Пони зеленый",
		color:  "Розовый",
        kind:   "Кирин",
		price:  "199.18",
		is_new: false,
    },
	{
		id:     30,
		name:   "Пони-принц",
		color:  "Желтый",
        kind:   "Кирин",
		price:  "250.00",
		is_new: true,
    },
]

